version: "2"

networks:
  app-network:
    driver: bridge

services:
  bulletin-app:
    image: bulletin-app
    ports:
      - 8888:8888
    build:
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - bulletin-postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postman", "-h", "bulletin-postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  bulletin-postgres:
    image: postgres:alpine
    container_name: bulletin-postgres
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: files/env/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  bulletin-migration:
    image: bulletin-migration
    build:
      dockerfile: migration.dockerfile
    depends_on:
      - bulletin-postgres
    networks:
      - app-network
    profiles:
      - donotstart
  bulletin-seeding:
    image: bulletin-seeding
    build:
      dockerfile: seeder.dockerfile
    depends_on:
      - bulletin-postgres
    networks:
      - app-network
    profiles:
      - donotstart

nginx:
  image: nginx:latest
  volumes:
    - ./nginx-conf:/etc/nginx/nginx.conf:ro
  depends_on:
    - bulletin-app
  ports:
    - 4040:4040

volumes:
  postgres-data:
  nginx-conf: