version: "2"

networks:
  app-network:
    driver: bridge

services:
  bulletin-app:
    image: bulletin-app
    ports:
      - 8888:8888
    build:
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - bulletin-postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postman", "-h", "bulletin-postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  bulletin-postgres:
    image: postgres:latest
    container_name: bulletin-postgres
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=xixixi
      - POSTGRES_USER=orangganteng
      - POSTGRES_DB=bulletindb
  bulletin-migration:
    image: bulletin-migration
    build:
      dockerfile: migration.dockerfile
    depends_on:
      - bulletin-postgres
    networks:
      - app-network
    profiles:
      - donotstart
  bulletin-seeding:
    image: bulletin-seeding
    build:
      dockerfile: seeder.dockerfile
    depends_on:
      - bulletin-postgres
    networks:
      - app-network
    profiles:
      - donotstart