server:
  host: "0.0.0.0"
  port: "8080"
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5

postgres:
  host: "bulletin-postgres"
  port: "5432"
  dbname: "recepie_db"
  dbuser: "root"
  dbpass: ""