server:
  host: "0.0.0.0"
  port: "8080"
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5

postgres:
  host: "testhost"
  port: "5432"
  dbname: "bulletindb"
  dbuser: "bulletindb_owner"
  dbpass: "lDb07joiaytz"

redis:
  host: ""
  port: ""
  password: ""
  db: 0