server:
  host: "0.0.0.0"
  port: "8888"
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5

postgres:
  host: "postgres_bulletin"
  port: "5432"
  dbname: "bulletindb"
  dbuser: "orangganteng"
  dbpass: "xixixi"